/*
 * TipCalculator.java
 * 10 September 2020
 * Jonathan Mainhart - CMIS 242
 * Basic GUI Tip Calculator which calculates 15%, 20%, and 25% tips. Calls Tip.java
 * to calculate the tip. Buile with the assistance of my daughter Sophia.
 */
package tipCalc;

import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author jonmainhart
 */
public class TipCalculator extends javax.swing.JFrame {

    /**
     * Creates new form TipCalculator
     */
    public TipCalculator() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        mealCostLable = new javax.swing.JLabel();
        mealCost = new javax.swing.JTextField();
        serviceQualityBox = new javax.swing.JPanel();
        okayServiceButton = new javax.swing.JRadioButton();
        goodServiceButton = new javax.swing.JRadioButton();
        excellentServiceButton = new javax.swing.JRadioButton();
        tipAmountLabel = new javax.swing.JLabel();
        totalLabel = new javax.swing.JLabel();
        tipAmount = new javax.swing.JLabel();
        totalAmount = new javax.swing.JLabel();
        calculateTipButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mealCostLable.setText("Meal Cost:");

        serviceQualityBox.setBorder(javax.swing.BorderFactory.createTitledBorder("Service Quality"));

        buttonGroup1.add(okayServiceButton);
        okayServiceButton.setText("Okay (15%)");

        buttonGroup1.add(goodServiceButton);
        goodServiceButton.setSelected(true);
        goodServiceButton.setText("Good (20%)");

        buttonGroup1.add(excellentServiceButton);
        excellentServiceButton.setText("Excellent (25%)");

        javax.swing.GroupLayout serviceQualityBoxLayout = new javax.swing.GroupLayout(serviceQualityBox);
        serviceQualityBox.setLayout(serviceQualityBoxLayout);
        serviceQualityBoxLayout.setHorizontalGroup(
            serviceQualityBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(serviceQualityBoxLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(serviceQualityBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(okayServiceButton)
                    .addComponent(goodServiceButton)
                    .addComponent(excellentServiceButton))
                .addContainerGap(63, Short.MAX_VALUE))
        );
        serviceQualityBoxLayout.setVerticalGroup(
            serviceQualityBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(serviceQualityBoxLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(okayServiceButton)
                .addGap(18, 18, 18)
                .addComponent(goodServiceButton)
                .addGap(18, 18, 18)
                .addComponent(excellentServiceButton)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        tipAmountLabel.setText("Tip Amount: ");

        totalLabel.setText("Total:");

        totalAmount.setText(" ");

        calculateTipButton.setText("Calculate Tip");
        calculateTipButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculateTipButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(mealCostLable)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(mealCost))
                    .addComponent(serviceQualityBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(tipAmountLabel)
                            .addGap(18, 18, 18)
                            .addComponent(tipAmount))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(totalLabel)
                            .addGap(18, 18, 18)
                            .addComponent(totalAmount)))
                    .addComponent(calculateTipButton))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mealCostLable)
                    .addComponent(mealCost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(calculateTipButton)
                        .addGap(59, 59, 59)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tipAmountLabel)
                            .addComponent(tipAmount))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(totalLabel)
                            .addComponent(totalAmount)))
                    .addComponent(serviceQualityBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void calculateTipButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calculateTipButtonActionPerformed
        // creates an instance of Tip to calculate the tip and set the label text
        try {
            if (okayServiceButton.isSelected()) {
                Tip tip = new Tip(Double.parseDouble(mealCost.getText()), 0.15);
                tipAmount.setText(String.format("%.02f", tip.getTipAmount()));
                totalAmount.setText(String.format("%.02f",
                        Double.parseDouble(mealCost.getText()) + tip.getTipAmount()));
            } else if (goodServiceButton.isSelected()) {
                Tip tip = new Tip(Double.parseDouble(mealCost.getText()), 0.20);
                tipAmount.setText(String.format("%.02f", tip.getTipAmount()));
                totalAmount.setText(String.format("%.02f",
                        Double.parseDouble(mealCost.getText()) + tip.getTipAmount()));
            } else {
                Tip tip = new Tip(Double.parseDouble(mealCost.getText()), 0.25);
                tipAmount.setText(String.format("%.02f", tip.getTipAmount()));
                totalAmount.setText(String.format("%.02f",
                        Double.parseDouble(mealCost.getText()) + tip.getTipAmount()));
            }
        } catch (NumberFormatException nfe) {
            System.out.println("Exception Thrown " + nfe.getMessage());
            // popup user message
            JFrame frame = new JFrame();
            JOptionPane.showMessageDialog(frame,
                    "You Must Enter Numbers!");

        }
    }//GEN-LAST:event_calculateTipButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TipCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TipCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TipCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TipCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TipCalculator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton calculateTipButton;
    private javax.swing.JRadioButton excellentServiceButton;
    private javax.swing.JRadioButton goodServiceButton;
    private javax.swing.JTextField mealCost;
    private javax.swing.JLabel mealCostLable;
    private javax.swing.JRadioButton okayServiceButton;
    private javax.swing.JPanel serviceQualityBox;
    private javax.swing.JLabel tipAmount;
    private javax.swing.JLabel tipAmountLabel;
    private javax.swing.JLabel totalAmount;
    private javax.swing.JLabel totalLabel;
    // End of variables declaration//GEN-END:variables
}
